#!/bin/bash
WIFISSID=$1
WIFIPASS=$2
WIFIMODE=$3

if [ "$WIFIPASS" == "" ]; then
        echo "network={
                ssid=\"$WIFISSID\"
                key_mgmt=NONE
        }
        " > /etc/wpa_supplicant.conf
        #echo "OPEN"
else
        if [ ${#WIFIMODE} -gt 0 ]; then
                echo "network={
                ssid=\"$WIFISSID\"
                key_mgmt=NONE
                wep_key0=\"$WIFIPASS\"
                wep_tx_keyidx=0
                }
                " > /etc/wpa_supplicant.conf
                #echo "WEP"
        else
                wpa_passphrase "$WIFISSID" "$WIFIPASS" > /etc/wpa_supplicant.conf
                #echo "WPA"
        fi
fi

dhclient -r wlan0
pkill wpa_supplicant
ifdown --force wlan0
sleep 1
wpa_supplicant -c /etc/wpa_supplicant.conf -i wlan0 -B
sleep 1
dhclient -nw wlan0

#nmcli device wifi rescan ifname wlan0
#nmcli device wifi connect "$WIFISSID" password "$WIFIPASS" ifname wlan0
