#!/bin/bash
######################################################
##                                                  ##
## Credits to Mike Kazantsev and Re4son             ##
##                                                  ##
######################################################


sudo apt install python-systemd python3-systemd bridge-utils
sudo cp $(pwd)/bt-pan /usr/local/sbin/bt-pan
sudo cp $(pwd)/pan /usr/local/sbin/pan
sudo cp $(pwd)/BT-AP /usr/local/sbin/BT-AP
sudo cp $(pwd)/pan.netdev /etc/systemd/network/pan.netdev
sudo cp $(pwd)/pan.network /etc/systemd/network/pan.network
sudo cp $(pwd)/pan.service /etc/systemd/system/pan.service
sudo chmod +x /usr/local/sbin/bt-pan
sudo chmod +x /usr/local/sbin/pan
sudo chmod +x /usr/local/sbin/BT-AP
sudo systemctl daemon-reload
sudo systemctl restart systemd-networkd
sudo systemctl start pan
echo "Bluetooth PAN AP yuklendi"
